### ISSUE TITLE
Incorrect Stats generated for April - October 2016

### ISSUE THREAD

**Issue by blundell** [novoda/github-reports#43]
when doing this search request `is:pr author:eduardb updated:>2016-04-01` on one of our private repo's we get 61 PR's, but on gitHub reports spreadsheet it shows 14

**Comment by eduardb** [comment]
It's 61 on Project-D, 73 for the whole org: https://github.com/search?utf8=%E2%9C%93&q=org%3Anovoda+is%3Apr+author%3Aeduardb+updated%3A%3C2016-10-01&type=Issues&ref=searchresults

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
