### ISSUE TITLE
Fix task date range

### ISSUE THREAD

**Issue by frapontillo** [novoda/github-reports#5]
When retrieving statistics for users and tasks, I often see something like:
- task starts at 01-07-2016 at 00:00
- task ends at 06-07-2016 at 00:00

Therefore, events happening on the 06-07-2016 fall out of the task, while (I think) should be in it.

Example:
![image](https://cloud.githubusercontent.com/assets/1140238/17143362/0a1230fa-534b-11e6-9de5-6b392b34a647.png)
(second and third column are the task ranges, last one is the event date)

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
