### ISSUE TITLE
Webhook Exceptions

### ISSUE THREAD

**Issue by takecare** [novoda/github-reports#6]
The default behaviour for the webhooks lambda handler's internals is to bubble up exceptions up until they make the lambda fail.

This happens, for example, when an unsupported event/action is received. Given that we know we don't support certain actions we may want to "assume" it and code around them, so no exceptions are thrown and as a result the webhook delivery does not fail.

**Comment by eduardb** [comment]
We went for configuring the API Gateway in a way that it returns HTTP Status Code 304 for UnhandledEventExceptions, code 500 for any other Exceptions, and 200 for no exceptions.

**Comment by frapontillo** [comment]
@eduardb can you share the details of the configuration in the README?
